[package]
name = "data_engine_columnar"
version.workspace = true
authors.workspace = true
repository.workspace = true
license = "Apache-2.0"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arrow = "55"

thiserror = { workspace = true }